# Generated by Django 4.1.4 on 2023-02-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="User",
            new_name="Passwords",
        ),
    ]
